export { deriveId, migrateCatalog } from './migrate.js';
export { addPage, updatePage, tombstonePage, movePage, toggleLock, setDepth } from './node-ops.js';
export { buildCatalogTree } from './tree.js';
export type { CatalogTree, CatalogTreeSection, CatalogTreeGroup } from './tree.js';
export { jaccard, pageContentEqual, alignRemote, CONCEPT_THRESHOLD, FINGERPRINT_THRESHOLD } from './align.js';
export { computeMergePlan } from './merge.js';
export type { MergeInput } from './merge.js';
export { loadBaseFromSnapshot } from './base-loader.js';
export { applyMergePlan } from './apply.js';
export type { MergeDecisions, ApplyResult } from './apply.js';
export { saveScope, listScopes, loadScope, resolveScope } from './scopes.js';
